# Generated by Django 2.2.3 on 2019-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('total_played', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('top_score', models.IntegerField()),
                ('avg_score', models.IntegerField()),
                ('player_level', models.CharField(default='Amateur', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
