# Generated by Django 2.2.3 on 2019-09-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
